use bindings::types::*;

/* automatically generated by rust-bindgen */

pub enum Struct__aio { }
pub type mraa_aio_context = *mut Struct__aio;
#[link(name = "mraa")]
extern "C" {
    pub fn mraa_aio_init(pin: ::libc::c_uint) -> mraa_aio_context;
    pub fn mraa_aio_read(dev: mraa_aio_context) -> ::libc::c_uint;
    pub fn mraa_aio_read_float(dev: mraa_aio_context) -> ::libc::c_float;
    pub fn mraa_aio_close(dev: mraa_aio_context) -> mraa_result_t;
    pub fn mraa_aio_set_bit(dev: mraa_aio_context, bits: ::libc::c_int)
     -> mraa_result_t;
    pub fn mraa_aio_get_bit(dev: mraa_aio_context) -> ::libc::c_int;
}
