use bindings::types::*;
/* automatically generated by rust-bindgen */

pub type mraa_boolean_t = ::libc::c_uint;
#[link(name = "mraa")]
extern "C" {
    pub fn mraa_init() -> mraa_result_t;
    pub fn mraa_deinit() -> ();
    pub fn mraa_pin_mode_test(pin: ::libc::c_int, mode: mraa_pinmodes_t)
     -> mraa_boolean_t;
    pub fn mraa_adc_raw_bits() -> ::libc::c_uint;
    pub fn mraa_adc_supported_bits() -> ::libc::c_uint;
    pub fn mraa_set_log_level(level: ::libc::c_int) -> mraa_result_t;
    pub fn mraa_get_platform_name() -> *mut ::libc::c_char;
    pub fn mraa_set_priority(priority: ::libc::c_uint) -> ::libc::c_int;
    pub fn mraa_get_version() -> *const ::libc::c_char;
    pub fn mraa_result_print(result: mraa_result_t) -> ();
    pub fn mraa_get_platform_type() -> mraa_platform_t;
    pub fn mraa_get_pin_count() -> ::libc::c_uint;
    pub fn mraa_get_pin_name(pin: ::libc::c_int) -> *mut ::libc::c_char;
}
